### ISSUE TITLE
图片替换远程图片地址加载1秒左右最终合成的图片显示暂无图片

### ISSUE THREAD

**Issue by 617450941** [psoho/fast-poster#11]
图片替换远程图片地址加载时长1秒左右 第一次访问会出现最终合成的图片显示暂无图片 要第二次访问才显示正常  能否延长远程加载图片的超时时间

**Comment by 617450941** [comment]
![image](https://user-images.githubusercontent.com/7607957/215318417-a3ea3b86-6998-41c8-8f9d-b8f736757bd4.png)

**Comment by tangweixin** [comment]
这个可以根据自己的实际情况，直接修改即可。演示环境设置的超时时间比较短。
