### ISSUE TITLE
[Warning] Stored XSS in fast-poster v2.15.0

### ISSUE THREAD

**Issue by Leeyangee** [psoho/fast-poster#13]
Vulnerability Product:fast-poster v2.15.0
Vulnerability version: v2.15.0
Vulnerability type: Stored XSS
Vulnerability Details:
Vulnerability location: /api/upload

File upload check binary of img, but without strictly check file suffix at /server/fast.py -> ApiUploadHandler.post，causes stored XSS
![image](https://github.com/psoho/fast-poster/assets/101627018/d243d40f-0f34-4379-9a0d-83f62ffb99f0)

Firstly we preparing a image payload(contain javascript code last line)↓
![image](https://github.com/psoho/fast-poster/assets/101627018/26be9adc-eb11-4c0e-8847-788006fe7235)
when you access the payload in image format, it is a img
when you access the payload in html format, it will execute code
payload : https://github.com/Leeyangee/leeya_bug/blob/main/payload.jpg

build project or go to https://poster.prodapi.cn/#/, choose a random post such as
<img width="900" alt="image" src="https://github.com/psoho/fast-poster/assets/101627018/9ed43fa5-7309-4f71-994c-2e0fe31dbf29">
click "上传" 
<img width="661" alt="image" src="https://github.com/psoho/fast-poster/assets/101627018/68cb319f-ab82-41a7-8ef4-ed1dbdee1e85">
choose payload.jpg, before upload , turn on intercept (take burpsuite as an example)
![image](https://github.com/psoho/fast-poster/assets/101627018/2d153be6-687b-4467-8687-5860a1900521)
when uploading , change payload.jpg
<img width="629" alt="image" src="https://github.com/psoho/fast-poster/assets/101627018/9108730a-0a73-4857-8b22-6ea2aa07a1ca">
to payload.html
<img width="455" alt="image" src="https://github.com/psoho/fast-poster/assets/101627018/446a9b4f-2376-4683-b774-21b6dbb5d697">
forward it , turn off intercept

After all, go to the path store/upload/20230706/168beb5822ad77d9.html
<img width="656" alt="image" src="https://github.com/psoho/fast-poster/assets/101627018/0219f201-5ef8-4ec7-b20c-f7ba0934a77a">
![image](https://github.com/psoho/fast-poster/assets/101627018/be7ada50-670f-4b44-aa20-39e19c2249c8)
successfully proved stored xss

discoverd by leeya_bug

**Comment by tangweixin** [comment]
This vulnerability cannot be reproduced in the fastposter desgin.

<img width="1675" alt="image" src="https://github.com/psoho/fast-poster/assets/897400/7dbcb288-cfa3-42d4-b6e8-230e92bd5b11">

You must open a new window to display the alert content

**Comment by tangweixin** [comment]
Thank you for your feedback
