### ISSUE TITLE
本机器按照 Docker方式启动，部署成功但无法访问 403

### ISSUE THREAD

**Issue by listener-He** [psoho/fast-poster#15]
docker run -it --name fastposter -p 5000:5000 fastposter/fastposter

系统：macos

<img width="578" alt="image" src="https://github.com/psoho/fast-poster/assets/39252579/dddd9230-41a6-47f6-b574-375ca5a14bbb">

**Comment by tangweixin** [comment]
刚刚试了一下，是可以正常启动的，建议您删除掉旧的镜像，重新拉取最新的试试。

```bash
docker images
```

再次尝试运行：
```bash
docker run -it --name fastposter -p 5000:5000 fastposter/fastposter
```

启动结果：

<img width="749" alt="image" src="https://github.com/psoho/fast-poster/assets/897400/6a4c901c-ccc1-4495-a923-f13f34c00130">


运行结果：
<img width="1710" alt="image" src="https://github.com/psoho/fast-poster/assets/897400/6ac5cdae-0d4e-4715-9013-8a4f8179cf4e">


如果还有问题，可以添加作者微信 `fastposter` 方便及时沟通。
